### ISSUE TITLE
Getting the content of the AppleScript in a readable format

### ISSUE THREAD

**Issue by jaepetto** [stackedsax/taskwarrior_scripts#1]
Hi,

first of all, thanks for sharing this repo.
Would it be possible to get a 'readable' version of the AppleScript file?
It would be really nice to see how it works and potentially propose a PR.

Thanks in advance,

Emmanuel

**Comment by jaepetto** [comment]
Sorry. My bad! I simply had to open it with the script editor...

**Comment by stackedsax** [comment]
@jaepetto Glad you got it!  Let me know if it actually still works for you -- it's been a while since I was in the corporate arena and trying to integrate with Outlook.

**Comment by jaepetto** [comment]
Yes. It does work. Thanks for the follow-up.
